routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return view('/lead');
    } else {
        return view('auth.login');
    }
});

Auth::routes();

//Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/lead', 'LeadController@index')->name('lead')->middleware('can:edit_lead');
Route::get('/construction', 'ConstructionController@index')->name('construction')->middleware('can:edit_lead');

// Route::prefix('admin')->group(function () { // original
Route::prefix('admin')->middleware('auth')->group(function () { // redirect to login if logged out
//Route::prefix('admin')->middleware('can:register_user')->group(function () {

    //dd($role = Auth::user()->role);
    
    Route::get('/', function () {
        return redirect('/admin/dashboard');
    });
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/users','Admin\UserController');
    
    // Trucker leads
    Route::get('/leads/import', 'Admin\ImportLeadsController@index')->name('leads.import');
    Route::get('/import-leads', 'Admin\ImportLeadsController@index')->name('leads.import');  // Not really needed
    Route::post('/import-leads', 'Admin\ImportLeadsController@import')->name('import-leads');
    Route::get('/import-leads/progress', 'Admin\ImportLeadsController@progress')->name('leads.progress');
    Route::resource('/leads','Admin\LeadController');
    
    // Construction leads
    Route::get('/constructions/import', 'Admin\ImportConstructionsController@index')->name('constructions.import');
    Route::get('/import-constructions', 'Admin\ImportConstructionsController@index')->name('constructions.import');  // Not really needed
    Route::post('/import-constructions', 'Admin\ImportConstructionsController@import')->name('import-constructions');
    Route::get('/import-constructions/progress', 'Admin\ImportConstructionsController@progress')->name('constructions.progress');
    Route::resource('/constructions','Admin\ConstructionController');
    
    Route::resource('/brokers','Admin\BrokerController');
    Route::get('/recent-activities', 'Admin\ApiRequestLogController@index');
    Route::get('/email-log', 'Admin\SentEmailsLogController@index');
    Route::get('/import-error-log', 'Admin\ImportErrorLogController@index')->name('import-log');
    
    // Route::view('/ui', 'admin.ui');
});

Route::get('/clear-cache', 'ClearCacheController@index');
Route::get('/db-migrate', 'DbMigrateController@index')->middleware('can:register_user');

app/Broker.php
<?php

namespace App;

use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;

class Broker extends Model
{
    use Filterable;
    use Notifiable;
    use Sortable;
    
    protected $guarded = [];


    public function setStatesCoveredAttribute($value)
    {
        $this->attributes['states_covered'] = json_encode($value);
    }
  
    public function getStatesCoveredAttribute($value)
    {
        return $this->attributes['states_covered'] = json_decode($value);
    }

    public function setAcceptedLanguagesAttribute($value)
    {
        $this->attributes['accepted_languages'] = json_encode($value);
    }
  
    public function getAcceptedLanguagesAttribute($value)
    {
        return $this->attributes['accepted_languages'] = json_decode($value);
    }
}

app/Http/Controllers/Admin/BrokerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Mail\WelcomeMail;
use App\Http\Controllers\Controller;
use App\Broker;

class BrokerController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:register_user');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $brokers = Broker::sortable()
            ->filter($request->all())
            ->paginate(15);

        return view('admin.brokers.index', compact('brokers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $states = config('constants.states');

        return view('admin.brokers.create', compact('states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'broker_name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'speed_dial' => ['required', 'string', 'max:255'],
            'preferred_comm_service' => ['required', 'string', 'max:255'],
            'contact_first_name' => ['required', 'string', 'max:255'],
            'contact_last_name' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'string', 'max:20'],
        ]);

        $broker = Broker::create($request->all());   

        notify()->success('Broker created!');

        return redirect()->route('brokers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $states = config('constants.states');
        $data = Broker::where('id', $id)->first();
        $broker = json_decode($data);

        return view('admin.brokers.edit', compact('broker', 'states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Broker $broker)
    {
        $request->validate([
            'broker_name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'speed_dial' => ['required', 'string', 'max:255'],
            'preferred_comm_service' => ['required', 'string', 'max:255'],
            'contact_first_name' => ['required', 'string', 'max:255'],
            'contact_last_name' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'string', 'max:20'],
        ]);

        try {
            $broker->update($request->all());
            notify()->success('Broker updated!');
        } catch (\Exception $error) {
            dd($error);
        }

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Broker $broker)
    {
        $broker->delete();
        notify()->success('Broker deleted!');

        return redirect()->route('brokers.index');
    }
}

resources/views/admin/brokers/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>CREATE BROKER</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="form-container">
                <form method="POST" action="{{ route('brokers.store') }}">
                    @csrf
                    {{-- @method('PUT') --}}

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="broker_name">Broker Name <span>*</span></label>
                            <input type="text" class="form-control" id="broker_name" name="broker_name" value="{{ old('broker_name') }}" required autofocus>
                            @error('broker_name')
                            <small class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="speed_dial">Speed Dial <span>*</span></label>
                            <input type="text" class="form-control" id="speed_dial" name="speed_dial" value="{{ old('speed_dial') }}" required>
                            @error('speed_dial')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="preferred_comm_service">Preferred Communication Service <span>*</span></label>
                            <input type="text" class="form-control" id="preferred_comm_service" name="preferred_comm_service" value="{{ old('preferred_comm_service') }}" required>
                            @error('preferred_comm_service')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="contact_first_name">Contact Person <span>*</span></label>
                            <input type="text" class="form-control" id="contact_first_name" name="contact_first_name" value="{{ old('contact_first_name') }}" placeholder="First Name" required>
                            @error('contact_first_name')
                            <small class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror
                        </div>
                        <div class="form-group col-md-2">
                            <label for="contact_last_name">&nbsp;</label>
                            <input type="text" class="form-control" id="contact_last_name" name="contact_last_name" value="{{ old('contact_last_name') }}" placeholder="Last Name" required>
                            @error('contact_last_name')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="phone">Phone Number <span>*</span></label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{ old('phone') }}" required>
                            @error('phone')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="email">Email <span>*</span></label>
                            <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
                            @error('email')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="min_number_of_trucks">Number of Trucks</label>
                            <input type="number" min="0" class="form-control" id="min_number_of_trucks" name="min_number_of_trucks" value="{{ old('min_number_of_trucks') }}" placeholder="Min" required>
                            @error('min_number_of_trucks')
                            <small class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror
                        </div>
                        <div class="form-group col-md-2">
                            <label for="max_number_of_trucks">&nbsp;</label>
                            <input type="number" min="0" class="form-control" id="max_number_of_trucks" name="max_number_of_trucks" value="{{ old('max_number_of_trucks') }}" placeholder="Max" required>
                            @error('max_number_of_trucks')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="daily_max_number_of_leads" data-toggle="tooltip" data-placement="right" title="Maximum number of leads that broker can take in one day">Daily Limit</label>
                            <input type="number" min="0" class="form-control" id="daily_max_number_of_leads" name="daily_max_number_of_leads" value="{{ old('daily_max_number_of_leads') }}" required>
                            @error('daily_max_number_of_leads')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="min_years_of_experience" data-toggle="tooltip" data-placement="right" title="Minimum required years in business for a lead">Years of Experience</label>
                            <input type="number" min="0" class="form-control" id="min_years_of_experience" name="min_years_of_experience" value="{{ old('min_years_of_experience') }}" required>
                            @error('min_years_of_experience')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label><strong>State(s) Covered</strong></label><br/>
                            <select class="form-control" name="states_covered[]" multiple size="10">
                                @foreach($states as $key => $value)
                                <option value="{{$key}}" {{old("states_covered[]") == $key ? 'selected' : ''}}>{{ $value }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label><strong>Language(s)</strong></label><br/>
                            <select class="form-control" name="accepted_languages[]" multiple size="2">
                                <option value="en" selected>English</option>
                                <option value="es">Spanish</option>
                            </select>
                        </div>
                    </div>

                    
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-primary btn-lg" style="float: right">Create Broker</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-js-script')
<script type="text/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>
@endsection

resources/views/admin/brokers/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>EDIT BROKER / {{ $broker->broker_name }}</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="form-container">
                <form method="POST" action="{{ route('brokers.update', $broker->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="broker_name">Broker Name <span>*</span></label>
                            <input type="text" value="{{ $broker->broker_name }}" class="form-control" id="broker_name" name="broker_name" value="{{ old('broker_name') }}" required autofocus>
                            @error('broker_name')
                            <small class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="speed_dial">Speed Dial <span>*</span></label>
                            <input type="text" value="{{ $broker->speed_dial }}" class="form-control" id="speed_dial" name="speed_dial" value="{{ old('speed_dial') }}" required>
                            @error('speed_dial')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="preferred_comm_service">Preferred Communication Service <span>*</span></label>
                            <input type="text" value="{{ $broker->preferred_comm_service }}" class="form-control" id="preferred_comm_service" name="preferred_comm_service" value="{{ old('preferred_comm_service') }}" required>
                            @error('preferred_comm_service')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="contact_first_name">Contact Person <span>*</span></label>
                            <input type="text" value="{{ $broker->contact_first_name }}" class="form-control" id="contact_first_name" name="contact_first_name" value="{{ old('contact_first_name') }}" placeholder="First Name" required>
                            @error('contact_first_name')
                            <small class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror
                        </div>
                        <div class="form-group col-md-2">
                            <label for="contact_last_name">&nbsp;</label>
                            <input type="text" value="{{ $broker->contact_last_name }}" class="form-control" id="contact_last_name" name="contact_last_name" value="{{ old('contact_last_name') }}" placeholder="Last Name" required>
                            @error('contact_last_name')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="phone">Phone Number <span>*</span></label>
                            <input type="text" value="{{ $broker->phone }}" class="form-control" id="phone" name="phone" value="{{ old('phone') }}" required>
                            @error('phone')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="email">Email <span>*</span></label>
                            <input type="email" value="{{ $broker->email }}" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
                            @error('email')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="min_number_of_trucks">Number of Trucks</label>
                            <input type="number" min="0" value="{{ $broker->min_number_of_trucks }}" class="form-control" id="min_number_of_trucks" name="min_number_of_trucks" value="{{ old('min_number_of_trucks') }}" placeholder="Min" required>
                            @error('min_number_of_trucks')
                            <small class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror
                        </div>
                        <div class="form-group col-md-2">
                            <label for="max_number_of_trucks">&nbsp;</label>
                            <input type="number" min="0" value="{{ $broker->max_number_of_trucks }}" class="form-control" id="max_number_of_trucks" name="max_number_of_trucks" value="{{ old('max_number_of_trucks') }}" placeholder="Max" required>
                            @error('max_number_of_trucks')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="daily_max_number_of_leads" data-toggle="tooltip" data-placement="right" title="Maximum number of leads that broker can take in one day">Daily Limit</label>
                            <input type="number" min="0" value="{{ $broker->daily_max_number_of_leads }}" class="form-control" id="daily_max_number_of_leads" name="daily_max_number_of_leads" value="{{ old('daily_max_number_of_leads') }}" required>
                            @error('daily_max_number_of_leads')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="min_years_of_experience" data-toggle="tooltip" data-placement="right" title="Minimum required years in business for a lead">Years of Experience</label>
                            <input type="number" min="0" value="{{ $broker->min_years_of_experience }}" class="form-control" id="min_years_of_experience" name="min_years_of_experience" value="{{ old('min_years_of_experience') }}" required>
                            @error('min_years_of_experience')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label><strong>State(s) Covered</strong></label><br/>
                            <select class="form-control" name="states_covered[]" multiple size="10">
                                @foreach($states as $key => $value)
                                <option value="{{$key}}" {{in_array($key, $broker->states_covered) ? 'selected' : ''}}>{{ $value }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label><strong>Language(s)</strong></label><br/>
                            <select class="form-control" name="accepted_languages[]" multiple size="2">
                                <option value="en" {{in_array("en", $broker->accepted_languages) ? 'selected' : ''}}>English</option>
                                <option value="es" {{in_array("es", $broker->accepted_languages) ? 'selected' : ''}}>Spanish</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-primary btn-lg" style="float: right">Update Broker</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/brokers/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>BROKERS</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-lg-12">
            <div class="form-container" style="float: left">
                <form class="form-inline" method="GET">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search" name="search" placeholder="Broker Name" value="{{$search ?? ''}}">
                    </div>
                    <button type="submit" class="btn btn-default">Filter</button>
                </form>
            </div>
            <div class="form-group" style="float: right">
                <a href="{{ route('brokers.create') }}" class="btn btn-primary">Create Broker</a>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>@sortablelink('id', 'ID')</th>
                        <th>@sortablelink('broker_name', 'Broker Name')</th>
                        <th>@sortablelink('speed_dial', 'Speed Dial')</th>
                        <th>@sortablelink('phone', 'Phone Number')</th>
                        <th>@sortablelink('email', 'Email')</th>
                        <th>@sortablelink('preferred_comm_service', 'Preferred Channel')</th>
                        <th>@sortablelink('created_at', 'Created')</th>
                        <th>@sortablelink('updated_at', 'Updated')</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($brokers as $broker)
                    <tr>
                        <td>{{ $broker->id ?? 'n/a' }}</td>
                        <td>{{ $broker->broker_name ?? 'n/a' }}</td>
                        <td>{{ $broker->speed_dial ?? 'n/a' }}</td>
                        <td>{{ $broker->phone ?? 'n/a' }}</td>
                        <td>{{ $broker->email ?? 'n/a' }}</td>
                        <td>{{ $broker->preferred_comm_service ?? 'n/a' }}</td>
                        <td>{{ $broker->created_at ?? 'n/a' }}</td>
                        <td>{{ $broker->updated_at ?? 'n/a' }}</td>
                        <td>
                            <form action="{{ route('brokers.destroy', $broker->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <a class="btn btn-primary" href="{{ route('brokers.edit', $broker->id) }}">Edit</a>
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this broker?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $brokers->appends(Request::except('page'))->render() !!}
        </div>
    </div>
</div>
@endsection