routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return view('/lead');
    } else {
        return view('auth.login');
    }
});

Auth::routes();

//Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/lead', 'LeadController@index')->name('lead')->middleware('can:edit_lead');
Route::get('/construction', 'ConstructionController@index')->name('construction')->middleware('can:edit_lead');

// Route::prefix('admin')->group(function () { // original
Route::prefix('admin')->middleware('auth')->group(function () { // redirect to login if logged out
//Route::prefix('admin')->middleware('can:register_user')->group(function () {

    //dd($role = Auth::user()->role);
    
    Route::get('/', function () {
        return redirect('/admin/dashboard');
    });
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/users','Admin\UserController');
    
    // Trucker leads
    Route::get('/leads/import', 'Admin\ImportLeadsController@index')->name('leads.import');
    Route::get('/import-leads', 'Admin\ImportLeadsController@index')->name('leads.import');  // Not really needed
    Route::post('/import-leads', 'Admin\ImportLeadsController@import')->name('import-leads');
    Route::get('/import-leads/progress', 'Admin\ImportLeadsController@progress')->name('leads.progress');
    Route::resource('/leads','Admin\LeadController');
    
    // Construction leads
    Route::get('/constructions/import', 'Admin\ImportConstructionsController@index')->name('constructions.import');
    Route::get('/import-constructions', 'Admin\ImportConstructionsController@index')->name('constructions.import');  // Not really needed
    Route::post('/import-constructions', 'Admin\ImportConstructionsController@import')->name('import-constructions');
    Route::get('/import-constructions/progress', 'Admin\ImportConstructionsController@progress')->name('constructions.progress');
    Route::resource('/constructions','Admin\ConstructionController');
    
    Route::resource('/brokers','Admin\BrokerController');
    Route::get('/recent-activities', 'Admin\ApiRequestLogController@index');
    Route::get('/email-log', 'Admin\SentEmailsLogController@index');
    Route::get('/import-error-log', 'Admin\ImportErrorLogController@index')->name('import-log');
    
    // Route::view('/ui', 'admin.ui');
});

Route::get('/clear-cache', 'ClearCacheController@index');
Route::get('/db-migrate', 'DbMigrateController@index')->middleware('can:register_user');

resources/views/admin/blank.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>BLANK PAGE</h2>
        </div>
    </div>
    <hr />

</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row text-center">
        <div class="col-lg-12">
            <h2>ADMIN DASHBOARD</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-lg-12 ">
            <div class="alert alert-info">
                Welcome <strong>{{auth()->user()->name}}</strong>!
                {{$leadsSentCount}} leads were sent to the brokers yesterday.
            </div>
        </div>
    </div>
    <div class="row text-center pad-top">
        {{-- <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
            <div class="div-square">
                <a href="#">
                    <i class="fa fa-circle-o-notch fa-5x"></i>
                    <h4>Check Data</h4>
                </a>
            </div>
        </div> --}}
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
            <div class="div-square">
                <a href="{{ route('leads.index') }}">
                    <i class="fa fa-users fa-5x"></i>
                    <h4>See Leads</h4>
                </a>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
            <div class="div-square">
                <a href="{{ route('users.create') }}">
                    <i class="fa fa-user fa-5x"></i>
                    <h4>Register User</h4>
                </a>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
            <div class="div-square">
                <a href="{{ route('leads.create') }}">
                    <i class="fa fa-user fa-5x"></i>
                    <h4>Register Lead</h4>
                </a>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
            <div class="div-square">
                <a href="{{ route('brokers.create') }}">
                    <i class="fa fa-user fa-5x"></i>
                    <h4>Register Broker</h4>
                </a>
            </div>
        </div>
    </div>
    {{-- <div class="row">
        <div class="col-lg-12 ">
            <br />
            <div class="alert alert-danger">
                <strong>Want More Icons Free ? </strong>
                Checkout fontawesome website and use any icon
                <a
                    target="_blank"
                    href="http://fortawesome.github.io/Font-Awesome/icons/"
                    >Click Here</a
                >.
            </div>
        </div>
    </div> --}}    
</div>
@endsection

resources/views/admin/email-log.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>EMAIL LOG</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="form-container">
                <form class="form-inline" method="GET">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search" name="search" placeholder="User Name" value="{{$search ?? ''}}">
                    </div>
                    <button type="submit" class="btn btn-default">Filter</button>
                </form>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>@sortablelink('id', 'ID')</th>
                        <th>@sortablelink('user.name', 'User')</th>
                        <th>@sortablelink('lead.legal_name', 'Lead')</th>
                        <th>@sortablelink('message_id', 'Message ID')</th>
                        <th>@sortablelink('type', 'Email Type')</th>                        
                        <th>@sortablelink('status', 'Email Status')</th> 
                        {{-- <th>Created</th> --}}
                        <th>@sortablelink('updated_at', 'Updated')</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($emailLog as $log)
                    <tr>
                        <td>{{ $log->id ?? 'n/a' }}</td>
                        <td>{{ $log->user->name ?? 'n/a' }}</td>
                        <td>{{ $log->lead->legal_name ?? 'n/a' }}</td>
                        <td>{{ $log->message_id ?? 'n/a' }}</td>
                        <td>{{ $log->type ?? 'n/a' }}</td>
                        <td>{{ $log->status ?? 'n/a' }}</td>
                        {{-- <td>{{ $log->created_at ?? 'n/a' }}</td> --}}
                        <td>{{ $log->updated_at ?? 'n/a' }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $emailLog->appends(Request::except('page'))->render() !!}
        </div>
    </div>
</div>
@endsection

resources/views/admin/import-error-log.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>IMPORT ERROR LOG</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-lg-12 col-md-12">
            {{-- <div class="form-container">
                <form class="form-inline" method="GET">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search" name="search" placeholder="User Name" value="{{$search ?? ''}}">
                    </div>
                    <button type="submit" class="btn btn-default">Filter</button>
                </form>
            </div> --}}
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>@sortablelink('id', 'ID')</th>
                        <th>@sortablelink('job_id', 'Job ID')</th>
                        <th>@sortablelink('row_number', 'Row')</th>
                        <th>Error Message</th>
                        {{-- <th>Created</th> --}}
                        <th>@sortablelink('created_at', 'Created')</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($errorLog as $log)
                    <tr>
                        <td>{{ $log->id ?? 'n/a' }}</td>
                        <td>{{ $log->job_id ?? 'n/a' }}</td>
                        <td>{{ $log->row_number ?? 'n/a' }}</td>
                        <td>{{ $log->message ?? 'n/a' }}</td>
                        {{-- <td>{{ $log->created_at ?? 'n/a' }}</td> --}}
                        <td>{{ $log->created_at ?? 'n/a' }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $errorLog->appends(Request::except('page'))->render() !!}
        </div>
    </div>
</div>
@endsection

resources/views/admin/recent-activities.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>RECENT ACTIVITIES</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="form-container">
                <form class="form-inline" method="GET">
                    <div class="form-group">
                        {{-- <label for="filter" class="col-sm-2 col-form-label">Filter</label> --}}
                        <input type="text" class="form-control" id="search" name="search" placeholder="User Name" value="{{$search ?? ''}}">
                    </div>
                    <button type="submit" class="btn btn-default">Filter</button>
                </form>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>@sortablelink('id', 'ID')</th>
                        <th>@sortablelink('user.name', 'User')</th>
                        <th>@sortablelink('lead.legal_name', 'Lead')</th>
                        <th>@sortablelink('lead.description', 'Type')</th>
                        <th>@sortablelink('response', 'Response ID')</th>
                        <th>@sortablelink('response_time', 'Response Time')</th>                        
                        <th>@sortablelink('created_at', 'Date')</th>
                        <th>BP Request</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($apiLog as $log)
                    <tr>
                        <td>{{ $log->id ?? 'n/a' }}</td>
                        <td>{{ $log->user->name ?? 'n/a' }}</td>
                        <td>{{ $log->lead->legal_name ?? 'n/a' }}</td>
                        <td>{{ $log->lead->description ?? 'n/a' }}</td>
                        <td>{{ $log->response ?? 'n/a' }}</td>
                        <td>{{ round($log->response_time, 2).' seconds' ?? 'n/a' }}</td>
                        <td>{{ $log->created_at ?? 'n/a' }}</td>
                        <td>
                            <button 
                                type="button" 
                                class="btn btn-primary" 
                                data-toggle="modal" 
                                data-name="{{ $log->user->name }}" 
                                data-date="{{ $log->created_at }}" 
                                data-request="{{ $log->request }}" 
                                data-target="#bp_request"
                            >
                                View
                            </button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{-- {{ $apiLog->links() }} --}}
            {!! $apiLog->appends(Request::except('page'))->render() !!}
        </div>
    </div>
</div>

<div class="modal fade" id="bp_request" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                {{-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button> --}}
            </div>
            <div class="modal-body">
                <dl id="request_dump" class="row"></dl>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-js-script')
<script type="text/javascript">
    $('#bp_request').on('show.bs.modal', function(e) {

        var request     = $.parseJSON(e.relatedTarget.dataset.request),
            data        = request.application_form.answer_values,
            name        = e.relatedTarget.dataset.name,
            date        = e.relatedTarget.dataset.date,
            modal       = $(this),
            dataLength  = data.length;

        modal.find(".modal-title").html(name + ' <strong>on</strong> ' + date);
        modal.find("#request_dump").html('');

        for (i = 0; i < dataLength; i++) {          
            modal.find("#request_dump").append(
                '<dt class="col-sm-6">' + data[i].code + '</dt>' + 
                '<dd class="col-sm-6">' + data[i].answer + '</dd>'
            );
        }
    });
</script>
@endsection