routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return view('/lead');
    } else {
        return view('auth.login');
    }
});

Auth::routes();

//Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/lead', 'LeadController@index')->name('lead')->middleware('can:edit_lead');
Route::get('/construction', 'ConstructionController@index')->name('construction')->middleware('can:edit_lead');

// Route::prefix('admin')->group(function () { // original
Route::prefix('admin')->middleware('auth')->group(function () { // redirect to login if logged out
//Route::prefix('admin')->middleware('can:register_user')->group(function () {

    //dd($role = Auth::user()->role);
    
    Route::get('/', function () {
        return redirect('/admin/dashboard');
    });
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/users','Admin\UserController');
    
    // Trucker leads
    Route::get('/leads/import', 'Admin\ImportLeadsController@index')->name('leads.import');
    Route::get('/import-leads', 'Admin\ImportLeadsController@index')->name('leads.import');  // Not really needed
    Route::post('/import-leads', 'Admin\ImportLeadsController@import')->name('import-leads');
    Route::get('/import-leads/progress', 'Admin\ImportLeadsController@progress')->name('leads.progress');
    Route::resource('/leads','Admin\LeadController');
    
    // Construction leads
    Route::get('/constructions/import', 'Admin\ImportConstructionsController@index')->name('constructions.import');
    Route::get('/import-constructions', 'Admin\ImportConstructionsController@index')->name('constructions.import');  // Not really needed
    Route::post('/import-constructions', 'Admin\ImportConstructionsController@import')->name('import-constructions');
    Route::get('/import-constructions/progress', 'Admin\ImportConstructionsController@progress')->name('constructions.progress');
    Route::resource('/constructions','Admin\ConstructionController');
    
    Route::resource('/brokers','Admin\BrokerController');
    Route::get('/recent-activities', 'Admin\ApiRequestLogController@index');
    Route::get('/email-log', 'Admin\SentEmailsLogController@index');
    Route::get('/import-error-log', 'Admin\ImportErrorLogController@index')->name('import-log');
    
    // Route::view('/ui', 'admin.ui');
});

Route::get('/clear-cache', 'ClearCacheController@index');
Route::get('/db-migrate', 'DbMigrateController@index')->middleware('can:register_user');

app/Construction.php
<?php

namespace App;

use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;

class Construction extends Model
{
    use Filterable;
    use Notifiable;
    use Sortable;
    
    protected $guarded = [];
}

app/Http/Controllers/Admin/ConstructionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Construction;

class ConstructionController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:register_user');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $constructions = Construction::sortable()
            ->filter($request->all())
            ->paginate(15);

        return view('admin.construction.index', compact('constructions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $states = config('constants.states');
        $legal_entities = config('constants.legal_entities');
        $coverage_types = config('constants.coverage_types');

        return view('admin.construction.create', compact('states', 'legal_entities', 'coverage_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'legal_name' => ['required', 'string', 'max:255'],
            'email_address' => ['nullable', 'string', 'email', 'max:255'],
            'phy_city' => ['required', 'string', 'max:255'],
            'phy_zip' => ['required', 'numeric', 'digits:5'],
            'phy_state' => ['required', 'string', 'max:255'],
            'first_name' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'numeric', 'digits:10'],
            'currently_insured' => ['required', 'string'],
        ]);

        $construction = Construction::create($request->all());

        notify()->success('Construction lead created!');

        return redirect()->route('constructions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $states = config('constants.states');
        $legal_entities = config('constants.legal_entities');
        $coverage_types = config('constants.coverage_types');

        $data = Construction::where('id', $id)->first();
        $construction = json_decode($data);

        return view('admin.constructions.edit', compact('construction', 'states', 'legal_entities', 'coverage_types'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Construction $construction)
    {
        $request->validate([
            'legal_name' => ['required', 'string', 'max:255'],
            'email_address' => ['nullable', 'string', 'email', 'max:255'],
            'phy_city' => ['required', 'string', 'max:255'],
            'phy_zip' => ['required', 'numeric', 'digits:5'],
            'phy_state' => ['required', 'string', 'max:255'],
            'first_name' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'numeric', 'digits:10'],
            'currently_insured' => ['required', 'string'],
        ]);

        try {
            $construction->update($request->all());
            notify()->success('Construction lead updated!');
        } catch (\Exception $error) {
            dd($error);
        }

        return redirect()->route('constructions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Construction $construction)
    {
        $construction->delete();
        notify()->success('Construction lead deleted!');

        return redirect()->route('constructions.index');
    }
}

app/Http/Controllers/ConstructionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Construction;
use Carbon\Carbon;

class ConstructionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('construction');
    }

    public function get(Request $id)
    {
        $term = $id->json()->all();
        $key = array_key_first($term);
        $value = reset($term);

        $construction = Construction::where($key, $value)->first();
        return response()->json($construction);
    }

    public function store($id, Request $request)
    {
        $request->validate([
            'legal_name'                          => 'required',
            'first_name'                          => 'required',
            // 'last_name'                           => 'required',
            'phone'                               => 'required|digits:10',
            'phy_city'                            => 'required',
            'phy_zip'                             => 'required|digits:5',
            'phy_state'                           => 'required|max:2',
            // 'phy_street'                          => 'required',
            'legal_entity'                        => 'nullable|string',
            'issue_date'                          => 'nullable|date',
            'expire_date'                         => 'nullable|date',
            'license_status'                      => 'nullable|string',
            'classifications'                     => 'nullable|string',
            'bond_carrier'                        => 'nullable|string',
            'bond_effective_date'                 => 'nullable|date',
            'workers_compensation_carrier'        => 'nullable|string',
            'workers_compensation_effective_date' => 'nullable|date',
            'liability_insurance_carrier'         => 'nullable|string',
            'liability_insurance_expiration_date' => 'nullable|date',
            'coverage_type'                       => 'nullable|string',
            'email_address'                       => 'nullable|email',
            'comment'                             => 'nullable|string',
        ]);

        $lead = Construction::where('id', $id)->update([
            'legal_name'                          => $request->legal_name,
            'first_name'                          => $request->first_name,
            'last_name'                           => $request->last_name,
            'scrape_name'                         => $request->scrape_name,
            'phone'                               => $request->phone,
            'phy_city'                            => $request->phy_city,
            'phy_zip'                             => $request->phy_zip,
            'phy_state'                           => $request->phy_state,
            'phy_street'                          => $request->phy_street,
            'legal_entity'                        => $request->legal_entity,
            'issue_date'                          => $request->issue_date,
            'expire_date'                         => $request->expire_date,
            'license_status'                      => $request->license_status,
            'classifications'                     => $request->classifications,
            'bond_carrier'                        => $request->bond_carrier,
            'bond_effective_date'                 => $request->bond_effective_date,
            'workers_compensation_carrier'        => $request->workers_compensation_carrier,
            'workers_compensation_effective_date' => $request->workers_compensation_effective_date,
            'liability_insurance_carrier'         => $request->liability_insurance_carrier,
            'liability_insurance_expiration_date' => $request->liability_insurance_expiration_date,
            'coverage_type'                       => $request->coverage_type,
            'email_address'                       => $request->email_address,
            'comment'                             => $request->comment,
        ]);

        return response()->json($lead);
    }

    public function delete($id)
    {
        Construction::destroy($id);

        return response()->json("ok");
    }
}

resources/views/admin/construction/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>Create construction lead</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="form-container">
                <form method="POST" action="{{ route('constructions.store') }}">
                    @csrf
                    {{-- @method('PUT') --}}

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="legal_name">Legal Name <span>*</span></label>
                            <input type="text" class="form-control" id="legal_name" name="legal_name" value="{{ old('legal_name') }}" required autofocus>
                            @error('legal_name')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-2">
                            <label for="first_name">First Name <span>*</span></label>
                            <input type="text" class="form-control" id="first_name" name="first_name" value="{{ old('first_name') }}" required>
                            @error('first_name')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-2">
                            <label for="last_name">Last Name</label>
                            <input type="text" class="form-control" id="last_name" name="last_name" value="{{ old('last_name') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="full_time_employees">Full Time Employees</label>
                            <input type="number" class="form-control" id="full_time_employees" name="full_time_employees" value="{{ old('full_time_employees') }}">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="email_address">Email</label>
                            <input type="email" class="form-control" id="email_address" name="email_address" value="{{ old('email_address') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="phone">Phone Number <span>*</span></label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{ old('phone') }}" required>
                            @error('phone')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="part_time_employees">Part Time Employees</label>
                            <input type="number" class="form-control" id="part_time_employees" name="part_time_employees" value="{{ old('part_time_employees') }}">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="phy_street">Street</label>
                            <input type="text" class="form-control" id="phy_street" name="phy_street" value="{{ old('phy_street') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="dba_name">DBA Name</label>
                            <input type="text" class="form-control" id="dba_name" name="dba_name" value="{{ old('dba_name') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="currently_insured">Currently Insured <span>*</span></label>
                            <select id="currently_insured" name="currently_insured" class="form-control" required>
                                <option {{old('currently_insured') == '' ? 'selected' : ''}}></option>
                                <option value="YES" {{old('currently_insured') == 'YES' ? 'selected' : ''}}>YES</option>
                                <option value="NO" {{old('currently_insured') == 'NO' ? 'selected' : ''}}>NO</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="phy_zip">ZIP Code <span>*</span></label>
                            <input type="text" class="form-control" id="phy_zip" name="phy_zip" value="{{ old('phy_zip') }}" required>
                            @error('phy_zip')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="phy_city">City <span>*</span></label>
                            <input type="text" class="form-control" id="phy_city" name="phy_city" value="{{ old('phy_city') }}" required>
                            @error('phy_city')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="years_of_experience">Part Time Employees</label>
                            <input type="number" class="form-control" id="years_of_experience" name="years_of_experience" value="{{ old('years_of_experience') }}">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="nbr_power_unit"># Trucks</label>
                            <input type="number" class="form-control" id="nbr_power_unit" name="nbr_power_unit" value="{{ old('nbr_power_unit') }}">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="driver_total"># Drivers</label>
                            <input type="number" class="form-control" id="driver_total" name="driver_total" value="{{ old('driver_total') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="phy_state">State <span>*</span></label>
                            <select id="phy_state" name="phy_state"  class="form-control" required>
                                @foreach($states as $key => $value)
                                <option value="{{$key}}" {{old('phy_state') == $key ? 'selected' : ''}}>{{ $value }}</option>
                                @endforeach
                            </select>
                            @error('phy_state')
                                <small class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </small>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="legal_entity">Legal Entity</label>
                            <select id="legal_entity" name="legal_entity" class="form-control">
                                @foreach($legal_entities as $key => $value)
                                <option value="{{$key}}" {{old('legal_entity') == $key ? 'selected' : ''}}>{{ $value }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="last_insurance_carrier">Last Insurance Carrier</label>
                            <input type="text" class="form-control" id="last_insurance_carrier" name="last_insurance_carrier" value="{{ old('last_insurance_carrier') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="dot_number">DOT Number</label>
                            <input type="text" class="form-control" id="dot_number" name="dot_number" value="{{ old('dot_number') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="coverage_type">Coverage Type</label>
                            <select id="coverage_type" name="coverage_type"  class="form-control">
                                @foreach($coverage_types as $key => $value)
                                <option value="{{$key}}" {{old('coverage_type') == $key ? 'selected' : ''}}>{{ $value }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="description">Description</label>
                            <input type="text" class="form-control" id="description" name="description" value="{{ old('description') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="last_insurance_date">Last Insurance Date</label>
                            <input type="date" class="form-control" id="last_insurance_date" name="last_insurance_date" value="{{ old('last_insurance_date') }}">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="insurance_cancellation_date">Insurance Cancelation Date</label>
                            <input type="date" class="form-control" id="insurance_cancellation_date" name="insurance_cancellation_date" value="{{ old('insurance_cancellation_date') }}">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="comment">Comment</label>
                            <textarea class="form-control" id="comment" name="comment" rows="3">{{ old('comment') }}</textarea>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-primary btn-lg" style="float: right">Create Construction Lead</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/construction/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>Constuction leads</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-lg-12">
            <div class="form-container" style="float: left">
                <form class="form-inline" method="GET">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search" name="search" placeholder="Legal Name" value="{{$search ?? ''}}">
                    </div>
                    <button type="submit" class="btn btn-default">Filter</button>
                </form>
            </div>
            <div class="form-group" style="float: right">
                <a href="{{ route('constructions.create') }}" class="btn btn-primary">Create Construction Lead</a>
                <a href="{{ route('constructions.import') }}" class="btn btn-success">Import Construction Leads</a>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>@sortablelink('id', 'ID')</th>
                        <th>@sortablelink('license_number', 'Licence Number')</th>
                        <th>@sortablelink('legal_name', 'Legal Name')</th>
                        <th>@sortablelink('email_address', 'Email')</th>
                        <th>@sortablelink('phone', 'Phone Number')</th>
                        <th>@sortablelink('state', 'State')</th>
                        <th>@sortablelink('created_at', 'Created')</th>
                        <th>@sortablelink('updated_at', 'Updated')</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($constructions as $construction)
                    <tr>
                        <td>{{ $construction->id ?? 'n/a' }}</td>
                        <td>{{ $construction->license_number ?? 'n/a' }}</td>
                        <td>{{ $construction->legal_name ?? 'n/a' }}</td>
                        <td>{{ $construction->email_address ?? 'n/a' }}</td>
                        <td>{{ $construction->phone ?? 'n/a' }}</td>
                        <td>{{ $construction->phy_state ?? 'n/a' }}</td>
                        <td>{{ $construction->created_at ?? 'n/a' }}</td>
                        <td>{{ $construction->updated_at ?? 'n/a' }}</td>
                        <td>
                            <form action="{{ route('constructions.destroy', $construction->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <a class="btn btn-primary" href="{{ route('constructions.edit', $construction->id) }}">Edit</a>
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this construction lead?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $constructions->appends(Request::except('page'))->render() !!}
        </div>
    </div>
</div>
@endsection