routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return view('/lead');
    } else {
        return view('auth.login');
    }
});

Auth::routes();

//Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/lead', 'LeadController@index')->name('lead')->middleware('can:edit_lead');
Route::get('/construction', 'ConstructionController@index')->name('construction')->middleware('can:edit_lead');

// Route::prefix('admin')->group(function () { // original
Route::prefix('admin')->middleware('auth')->group(function () { // redirect to login if logged out
//Route::prefix('admin')->middleware('can:register_user')->group(function () {

    //dd($role = Auth::user()->role);
    
    Route::get('/', function () {
        return redirect('/admin/dashboard');
    });
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/users','Admin\UserController');
    
    // Trucker leads
    Route::get('/leads/import', 'Admin\ImportLeadsController@index')->name('leads.import');
    Route::get('/import-leads', 'Admin\ImportLeadsController@index')->name('leads.import');  // Not really needed
    Route::post('/import-leads', 'Admin\ImportLeadsController@import')->name('import-leads');
    Route::get('/import-leads/progress', 'Admin\ImportLeadsController@progress')->name('leads.progress');
    Route::resource('/leads','Admin\LeadController');
    
    // Construction leads
    Route::get('/constructions/import', 'Admin\ImportConstructionsController@index')->name('constructions.import');
    Route::get('/import-constructions', 'Admin\ImportConstructionsController@index')->name('constructions.import');  // Not really needed
    Route::post('/import-constructions', 'Admin\ImportConstructionsController@import')->name('import-constructions');
    Route::get('/import-constructions/progress', 'Admin\ImportConstructionsController@progress')->name('constructions.progress');
    Route::resource('/constructions','Admin\ConstructionController');
    
    Route::resource('/brokers','Admin\BrokerController');
    Route::get('/recent-activities', 'Admin\ApiRequestLogController@index');
    Route::get('/email-log', 'Admin\SentEmailsLogController@index');
    Route::get('/import-error-log', 'Admin\ImportErrorLogController@index')->name('import-log');
    
    // Route::view('/ui', 'admin.ui');
});

Route::get('/clear-cache', 'ClearCacheController@index');
Route::get('/db-migrate', 'DbMigrateController@index')->middleware('can:register_user');

app/User.php
<?php

namespace App;

use EloquentFilter\Filterable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;

class User extends Authenticatable
{
    use Filterable;
    use Notifiable;
    use Sortable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'state', 'city'
    ];

    public $sortable = [
        'id',
        'name',
        'email',
        'created_at',
        'updated_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles() 
    {
        return $this->belongsToMany(Role::class)->withTimestamps();
    }

    public function assignRole($role)
    {
        if (is_string($role)) {
            $role = Role::whereName($role)->firstOrFail();
        }
        
        $this->roles()->sync($role, false);
    }

    public function abilities()
    {
        return $this->roles->map->abilities->flatten()->pluck('name')->unique();
    }

    public function emails()
    {
        return $this->hasMany(SentEmailsLog::class);
    }

    public function apiRequestLogs()
    {
        return $this->hasMany(ApiRequestLog::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Mail\WelcomeMail;
use App\Mail\UserEdited;
use App\Http\Controllers\Controller;
use App\User;
//use Config;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:register_user');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::with('roles')->sortable()
            ->filter($request->all())
            ->paginate(15);

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'ends_with:coveragecenter.net', 'string', 'email', 'max:255'],
            'role' => ['required', 'string', 'in:admin,agent'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        */
        
        $validator = \Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'ends_with:coveragecenter.net', 'string', 'email', 'max:255'],
            'role' => ['required', 'string', 'in:admin,agent'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        
        // Try to create email account
        $result = $this->createEmailAccount($request);
        if (!$result['success'])
        {
            $error = \Illuminate\Validation\ValidationException::withMessages([
               'email' => [$result['error']],
            ]);
            notify()->error($result['error']);
            throw $error;
        }

        $user = User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'phone' => $request['phone'],
            'city' => $request['city'],
            'state' => $request['state'],
            'password' => Hash::make($request['password']),
        ]);

        $user->assignRole($request['role']);

        Mail::send(new WelcomeMail($user));

        notify()->success('User created!');

        return redirect()->route('users.index');
    }
    
    /**
     * Create email address account for user.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function createEmailAccount(Request $request)
    {
        $cookie = "cookie-name";
        $url = env('CP_URL') . '/login/?login_only=1';
        $curl_request = [
            'user' => env('CP_USER'),
            'pass' => env('CP_PWD'),
            'goto_uri' => '/',
        ];
        $query = http_build_query($curl_request);

        // Create new curl handle
        $ch = curl_init();
        //curl_setopt($ch, CURLOPT_USERAGENT,'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/32.0.1700.107 Chrome/32.0.1700.107 Safari/537.36');
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_COOKIESESSION, true);
        //curl_setopt($ch, CURLOPT_COOKIEJAR, $cookie);
        curl_setopt($ch, CURLOPT_COOKIEFILE, $cookie);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
        curl_setopt($ch, CURLOPT_TIMEOUT, 100020);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        // Execute the curl handle and fetch info then close streams.
        $response = curl_exec($ch);
        $response = json_decode($response, true);
        // echo "response:<pre>";
        // print_r($response);
        // echo "</pre>";
        if (isset($response['security_token']))
        {
            $url = env('CP_URL') . $response['security_token'] . '/execute/Email/add_pop';
            $curl_request = [
                'email' => substr($request['email'], 0, strrpos($request['email'], '@')),
                'domain' => 'coveragecenter.net',
                'password' => $request['password'],
                'quota' => 2048,
                'send_welcome_email' => 0
            ];
            $query = http_build_query($curl_request);
            
            //another request preserving the session
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
            $response = curl_exec($ch);
            $response = json_decode($response, true);
            //echo "answer:<pre>";
            //print_r($answer);
            //echo "</pre>";
            if (!empty($response['errors']))
            {
                $response = [
                    'success' => false,
                    'error' => $response['errors'][0]
                ];
            }
            else
            {
                $response = [
                    'success' => true,
                    'message' => 'Mailbox successfully created.'
                ];
            }
        }
        else
        {
            $response = [
                'success' => false,
                'error' => 'Can\'t access mailbox creation API.'
            ];
        }
        curl_close($ch);
        
        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::where('id', $id)->with('roles')->first();
        $user = json_decode($data);

        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'role' => ['required', 'string', 'in:admin,agent'],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
        ]);
        
        $old_email = $user->email;
        $new_email = $request->get('email');
        if ($old_email !== $new_email)
        {
            if ($request->get('password') == '')
            {
                $error = \Illuminate\Validation\ValidationException::withMessages([
                   'password' => ['You need to specify password if user\'s email is changed.'],
                ]);
                notify()->error('You need to specify password if user\'s email is changed.');
                throw $error;
            }
            
            // Delete old email account
            $result = $this->deleteEmailAccount($user);
            
            // Create new email account
            $result = $this->createEmailAccount($request);
            if (!$result['success'])
            {
                $error = \Illuminate\Validation\ValidationException::withMessages([
                   'email' => [$result['error']],
                ]);
                notify()->error($result['error']);
                throw $error;
            }
        }

        if ($request->get('password') == '') {
            $user->update ($request->except('password'));
        } else {
            $user->update($request->all());
        }

        $user->assignRole($request['role']);

        Mail::send(new UserEdited($user)); 

        notify()->success('User updated!');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $result = $this->deleteEmailAccount($user);
        
        if (!$result['success'])
        {
            $error = \Illuminate\Validation\ValidationException::withMessages([
               'email' => [$result['error']],
            ]);
            notify()->error($result['error']);
            throw $error;
        }
        else
        {
            $user->delete();
            notify()->success('User deleted!');
            return redirect()->route('users.index');
        }
    }
    
    /**
     * Create email address account for user.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function deleteEmailAccount(User $user)
    {
        $cookie = "cookie-name";
        $url = env('CP_URL') . '/login/?login_only=1';
        $request = [
            'user' => env('CP_USER'),
            'pass' => env('CP_PWD'),
            'goto_uri' => '/',
        ];
        $query = http_build_query($request);

        // Create new curl handle
        $ch = curl_init();
        //curl_setopt($ch, CURLOPT_USERAGENT,'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/32.0.1700.107 Chrome/32.0.1700.107 Safari/537.36');
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>CREATE USER</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-8">
            <div class="form-container">
                <form method="POST" action="{{ route('users.store') }}">
                    @csrf

                    <div class="form-group row">
                        <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Name') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-3 col-form-label text-md-right">{{ __('E-Mail Address') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-3 col-form-label text-md-right">{{ __('Phone Number') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" autocomplete="phone">

                            @error('phone')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="city" class="col-md-3 col-form-label text-md-right">{{ __('City') }}</label>

                        <div class="col-md-6">
                            <input id="city" type="text" class="form-control @error('city') is-invalid @enderror" name="city" value="{{ old('city') }}" autocomplete="city">

                            @error('city')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="state" class="col-md-3 col-form-label text-md-right">{{ __('Country') }}</label>

                        <div class="col-md-6">
                            <input id="state" type="text" class="form-control @error('state') is-invalid @enderror" name="state" value="{{ old('state') }}" autocomplete="state">

                            @error('state')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="role" class="col-md-3 col-form-label text-md-right">Role <span>*</span></label>
                    
                        <div class="col-md-6">
                            <select name="role" class="form-control" >
                                <option value="agent">Agent</option>
                                <option value="admin">Admin</option>
                            </select> 
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="col-md-3 col-form-label text-md-right">{{ __('Password') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                            @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password-confirm" class="col-md-3 col-form-label text-md-right">{{ __('Confirm Password') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 col-md-offset-3">
                            <button type="submit" class="btn btn-primary btn-lg">
                                {{ __('Register') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>EDIT USER / {{ $user->name }}</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-8">
            <div class="form-container">
                <form method="POST" action="{{ route('users.update', $user->id) }}">
                    @csrf

                    @method('PUT')
                    <div class="form-group row">
                        <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Full Name') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="name" type="text" value="{{ $user->name }}" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-3 col-form-label text-md-right">{{ __('E-Mail Address') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="email" type="email" value="{{ $user->email }}" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-3 col-form-label text-md-right">{{ __('Phone Number') }} <span>*</span></label>

                        <div class="col-md-6">
                            <input id="phone" type="text" value="{{ $user->phone }}" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" autocomplete="phone">

                            @error('phone')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="city" class="col-md-3 col-form-label text-md-right">{{ __('City') }}</label>

                        <div class="col-md-6">
                            <input id="city" type="text" value="{{ $user->city }}" class="form-control @error('city') is-invalid @enderror" name="city" value="{{ old('city') }}" autocomplete="city">

                            @error('city')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="state" class="col-md-3 col-form-label text-md-right">{{ __('Country') }}</label>

                        <div class="col-md-6">
                            <input id="state" type="text" value="{{ $user->state }}" class="form-control @error('state') is-invalid @enderror" name="state" value="{{ old('state') }}" autocomplete="state">

                            @error('state')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="role" class="col-md-3 col-form-label text-md-right">Role <span>*</span></label>
                    
                        <div class="col-md-6">
                            <select name="role" class="form-control" >
                                <option value="agent" {{$user && $user->roles && $user->roles[0]->name == 'agent' ? 'selected' : ''}}>Agent</option>
                                <option value="admin" {{$user && $user->roles && $user->roles[0]->name == 'admin' ? 'selected' : ''}}>Admin</option>
                            </select> 
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="col-md-3 col-form-label text-md-right">{{ __('Password') }}</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autocomplete="new-password">

                            @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password-confirm" class="col-md-3 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                        <div class="col-md-6">
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" autocomplete="new-password">
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 col-md-offset-3">
                            <button type="submit" class="btn btn-primary btn-lg">
                                {{ __('Update') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div id="page-inner">
    <div class="row">
        <div class="col-lg-12">
            <h2>USERS</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-lg-12">
            <div class="form-container" style="float: left">
                <form class="form-inline" method="GET">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search" name="search" placeholder="User Name" value="{{$search ?? ''}}">
                    </div>
                    <button type="submit" class="btn btn-default">Filter</button>
                </form>
            </div>
            <div class="form-group" style="float: right">
                <a href="{{ route('users.create') }}" class="btn btn-primary">Create User</a>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>@sortablelink('id', 'ID')</th>
                        <th>@sortablelink('name', 'Name')</th>
                        <th>@sortablelink('roles', 'Role')</th>
                        <th>@sortablelink('email', 'Email')</th>
                        <th>@sortablelink('phone', 'Phone')</th>
                        <th>@sortablelink('city', 'City')</th>
                        <th>@sortablelink('state', 'State')</th>
                        <th>@sortablelink('created_at', 'Created')</th>
                        <th>@sortablelink('updated_at', 'Updated')</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id ?? 'n/a' }}</td>
                        <td>{{ $user->name ?? 'n/a' }}</td>
                        <td>{{ $user->roles ? $user->roles->pluck('name')->implode(', ') : 'n/a' }}</td>
                        <td>{{ $user->email ?? 'n/a' }}</td>
                        <td>{{ $user->phone ?? 'n/a' }}</td>
                        <td>{{ $user->city ?? 'n/a' }}</td>
                        <td>{{ $user->state ?? 'n/a' }}</td>
                        <td>{{ $user->created_at ?? 'n/a' }}</td>
                        <td>{{ $user->updated_at ?? 'n/a' }}</td>
                        <td>
                            <form action="{{ route('users.destroy', $user->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <a class="btn btn-primary" href="{{ route('users.edit', $user->id) }}">Edit</a>
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this user?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $users->appends(Request::except('page'))->render() !!}
        </div>
    </div>
</div>
@endsection